#!/usr/bin/python

'''
Motstat is a command-line application that provides information about current connections (much like netstat) and also 
live monitoring of internal counters. 

The command is implemented with this program. The script opens a TCP connection against a Mot context running in the
same host; the context is selected using the TCP port. 

All the output logic is done in the server-side: the client script merely sends the arguments and then tunnels the 
response.
'''

import sys, socket
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-p', '--port', type=int, help='port', default=6101)
parser.add_argument('tokens', nargs='*')
args = parser.parse_args()

timeout = 10000
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect(("localhost", args.port))
sock.settimeout(timeout)

sock.sendall(' '.join(args.tokens))
sock.shutdown(socket.SHUT_WR)
buffersize = 4096
try:
	data = sock.recv(buffersize)
	while data:
		sys.stdout.write(data)
		data = sock.recv(buffersize)
except KeyboardInterrupt:
	print
